<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.stacksaga</groupId>
    <artifactId>stacksaga-bom</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-cloud.version>2023.0.3</spring-cloud.version>
        <org-javatuples.version>1.2</org-javatuples.version>
        <jnanoid.version>2.0.0</jnanoid.version>
        <swagger.annotations.jakarta>2.2.16</swagger.annotations.jakarta>
        <io.github.completabletuples.version>2.0.0</io.github.completabletuples.version>
        <cron-utils.version>9.1.6</cron-utils.version>
        <lombok.version>1.18.32</lombok.version>

    </properties>

    <dependencyManagement>

        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.5.12</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2025.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>1.1.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-commons</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-starter-commons</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-spring-boot-starter</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-mysql-reactive-support</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-mysql-reactive-support-api</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-mysql-reactive-support-impl</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-cassandra-reactive-support</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-cassandra-reactive-support-impl</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-cassandra-reactive-support-api</artifactId>
                <version>1.0.0</version>
            </dependency>


            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-kafka-commons</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-kafka-worker-starter</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-kafka-orchestrator-starter</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-retry-reactive-support-api</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-retry-reactive-support-impl</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-retry-reactive-support</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-retry-reactive-discoveryclient-support</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-retry-reactive-dns-support</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-retry-dns-spring-boot-starter</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-retry-discoveryclient-spring-boot-starter</artifactId>
                <version>1.0.0</version>
            </dependency>


            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-ring-coordinator-connector-api</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-ring-coordinator-connector</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-ring-coordinator-starter</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-agent-mysql-starter</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-agent-mysql-core</artifactId>
                <version>1.0.0</version>
            </dependency>


            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-trace-window-connector-servlet</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-trace-window-connector-api</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-trace-window-connector-webflux</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-agent-connector</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-agent-connector-impl</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-agent-connector-api</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-env-discoveryclient-support</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-env-k8s-support</artifactId>
                <version>1.0.0</version>
            </dependency>

            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-source-cache-support</artifactId>
                <version>1.0.0</version>
            </dependency>



            <!--non stacksaga dependencies-->

            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations-jakarta</artifactId>
                <version>${swagger.annotations.jakarta}</version>
            </dependency>
            <dependency>
                <groupId>io.github.completabletuples</groupId>
                <artifactId>completable-tuples</artifactId>
                <version>${io.github.completabletuples.version}</version>
            </dependency>

            <dependency>
                <groupId>org.javatuples</groupId>
                <artifactId>javatuples</artifactId>
                <version>${org-javatuples.version}</version>
            </dependency>

            <dependency>
                <groupId>com.aventrix.jnanoid</groupId>
                <artifactId>jnanoid</artifactId>
                <version>${jnanoid.version}</version>
            </dependency>
            <dependency>
                <groupId>com.cronutils</groupId>
                <artifactId>cron-utils</artifactId>
                <version>${cron-utils.version}</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>

            <dependency>
                <groupId>org.liquibase.ext</groupId>
                <artifactId>liquibase-cassandra</artifactId>
                <version>4.29.1</version>
            </dependency>

            <dependency>
                <groupId>com.ing.data</groupId>
                <artifactId>cassandra-jdbc-wrapper</artifactId>
                <version>4.13.0</version>
            </dependency>

            <dependency>
                <groupId>com.scylladb</groupId>
                <artifactId>java-driver-core</artifactId>
                <version>4.18.0.2</version>
            </dependency>
            <dependency>
                <groupId>com.scylladb</groupId>
                <artifactId>java-driver-query-builder</artifactId>
                <version>4.18.0.2</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>