<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.stacksaga</groupId>
    <artifactId>stacksaga-bom</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-core</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-commons</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-starter-commons</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-spring-boot-starter</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-mysql-reactive-support</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-mysql-reactive-support-core</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-mysql-api-servlet</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-mysql-api-webflux</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-cassandra-reactive-support</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-cassandra-api-servlet</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-cassandra-api-webflux</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-kafka-commons</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-kafka-client</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-kafka-spring-boot-starter</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-retry-reactive-support-api</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-retry-reactive-support-impl</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-agent-cluster-coordinator-support-impl</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.stacksaga</groupId>
                <artifactId>stacksaga-agent-mysql-starter</artifactId>
                <version>1.0.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>